name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Install Cypress
        run: npm install cypress@9.5.1 --save-dev

      - name: Cypress run
        uses: cypress-io/github-action@v2